language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
before_install:
  - sudo add-apt-repository trusty-backports -y
  - sudo apt-get update -q
  - sudo apt-get install -y libxml2-dev libboost-dev libboost-regex-dev libtool doxygen graphviz swig3.0 python-dev ruby-dev
script: make -f Makefile.repo && make && make check
